Add Chinese Shape Based Layouts
florisboard/florisboard pull request #2054
Opened 2022-09-06 18:30 UTC by Waelwindows

This PR adds Chinese Hanzi shape based input to FlorisBoard, This should be a step towards #149 

Currently, this PR only implements the Zhengma layout (鄭碼輸入法) inside of the `ime/dict/han.sqlite3` database. The data was taken from [this repo](https://github.com/acevery/ibus-table-zhengma) although the data is now in the public domain.

The plan is to add the rest of the other shape based layouts inside of this database and select the appropriate table to suggest from using the secondary locales of the subtypes. e.g. `zh-zhengma`, `zh-cangjie`, etc...

One thing to note is that spaces are disabled in the PR, as CJK suggestions do not use spaces. However, the default keyboard layouts add spaces after committing suggestions via the smart menu or the spacebar.

So far, word frequency is not implemented, although it should be easy to add. Other than the above, this PR is usable as is for Chinese input, ~~although it bricks everything else because of spaces~~

Here's a video of it in action

https://user-images.githubusercontent.com/5228243/188711969-f28dd84e-ec78-4daa-a7ae-cccc4254c4bb.mp4

2022-09-07 21:24 UTC, patrickgold reviewed
Thanks a lot for your hard work, really appreciate it!

I sadly haven't gotten around to actually testing this out locally, however having a quick look at it it looks very promising.

Fr the spacing problem I've suggested one solution, if you have another my ears are open :)

2022-09-07 21:24 UTC, patrickgold commented on app/src/main/kotlin/dev/patrickgold/florisboard/ime/editor/EditorInstance.kt
> +        return false;
You could change this line to something like:

```suggestion
        if (subtypeManager.activeSubtype.language.startsWith("zh")) return false;
```

and comment everything else out and the spacing logic should work for all languages, including yours, correctly.

2022-09-07 21:24 UTC, patrickgold commented on app/src/main/kotlin/dev/patrickgold/florisboard/ime/keyboard/KeyboardManager.kt
> +        // editorInstance.commitText(KeyCode.SPACE.toChar().toString())
Same here, check for the active subtype language and then only conditionally execute this line.

2022-09-21 06:56 UTC, moonbeamcelery commented
Hi Waelwindows, thank you so much for this update, very excited! I tested this out but it turns out to be a pain not being able to switch between this layout and others, so I made changes and made a pull request to your branch.

I don't know how to do it, but one remaining issue is the suggestions is not changed when switching between layouts with different nlpProviders. It should be either cleared or re-calculated.

2022-09-22 16:39 UTC, moonbeamcelery commented on app/src/main/assets/ime/keyboard/org.florisboard.localization/extension.json
> +      "languageTag": "zh-RC-zhengma",
We probably need a way to specify the variant since people from all zh-* locales may use zhengma. Currently this is not accessible other than the suggested subtypes.

Right now, zh-RC is not in the locale dropdown, and a google search did not find anything. Did you mean zh-TW?

2022-09-22 17:15 UTC, moonbeamcelery commented on app/src/main/assets/ime/keyboard/org.florisboard.localization/extension.json
> +      "languageTag": "zh-RC-zhengma",
Right now the locale selection is just using Android's provided one and I'm not sure if there is a way to customize that. If not we may need to add a variant selection dropdown by ourselves.

2022-09-22 21:00 UTC, Waelwindows commented on app/src/main/assets/ime/keyboard/org.florisboard.localization/extension.json
> +      "languageTag": "zh-RC-zhengma",
Oops, that's my fault. I thought `RC` was a registered region code but turns out it's just [reserved](https://wikipedia.org/wiki/ISO_3166-1_alpha-2?lang=en#Indeterminate_reservations).

I'm conflicted on what the region code should be since zhengma supports simplified characters but the other most popular shape based method (cangjie) is mostly used in Taiwan. Any suggestions on this?

2022-09-23 03:49 UTC, moonbeamcelery commented on app/src/main/assets/ime/keyboard/org.florisboard.localization/extension.json
> +      "languageTag": "zh-RC-zhengma",
I don't really know, I would prefer the region to not be specified as well lol. If only `zh--zhengma` works. But if using a non-official region like zh-RC seems to work with the code, is it too hacky to use something random like `zh-ZH-zhengma`?

However, on second thought, there definitely are more settings specific to each input method. Like there are multiple versions of wubi, and if you look at gboard's settings, each input method has their own setting fields. Maybe instead of using the variant to describe the input method, we need to have a more complicated structure for that.

2022-09-23 07:05 UTC, wengtad commented on app/src/main/assets/ime/keyboard/org.florisboard.localization/extension.json
> +      "languageTag": "zh-RC-zhengma",
First of all, thanks for all of your hard works!

If the table provided in [Chinese.StackExchange](https://chinese.stackexchange.com/questions/43465/incomplete-list-of-free-chinese-input-methods-in-current-use/43924#43924) is correct then I think the Pinyin/Wubi/ZhengMa input method will be part under zh-CN. 

Language code for Chinese (source: [here](http://www.lingoes.net/en/translator/langcode.htm)) will be `zh` `zh-CN` `zh-HK` `zh-MO` `zh-SG` `zh-TW`.

Those just are my finding, hopes it help and welcomes to correct me if I'm wrong. :)

2022-11-01 23:37 UTC, patrickgold reviewed
So after a long time I am finally re-reviewing this PR again. First up thanks to everyone involved in helping getting this PR forward, really appreciate it!

I've only had the chance to read through the diffs yet but if I see it correctly there has been a lot of progress and it looks a lot more complete (together with #2093's fixes). Will test it out on a technical level on my devices later on, but it looks pretty promising.

There is still at least one blocking thing from me, the default provider being the HanShapeBased one. What we could do is to let this value be the Latin one and only while testing setting it to the HanShapeBased one for now. Before this merged PR makes it into an alpha release I will also merge in my NLP changes, with that I will find a quick'n'dirty solution for a runtime selection of the provider in the very first release with the new suggestions. (And subsequently make a clean version together with a new subtype screen UI and integrated provider selection in a later alpha release). Should you have a better approach for this I am also open-ears.

Also thanks for providing a NIX config file, even though I have no way of actually testing it it may be useful for other users who build this project in a NIX environment.

2022-11-01 23:37 UTC, patrickgold commented on app/src/main/kotlin/dev/patrickgold/florisboard/ime/core/Subtype.kt
> +    val suggestion: String = HanShapeBasedLanguageProvider.ProviderId,
Needs to be fixed before merging. Probably needs to be fixed by me in the main code base first by allowing a dynamic language provider selection.

2022-11-01 23:37 UTC, patrickgold commented on app/src/main/kotlin/dev/patrickgold/florisboard/ime/nlp/han/HanShapeBasedLanguageProvider.kt
> +        // Here we have the chance to preload dictionaries and prepare a neural network for a specific language.
These comments can be removed from this provider, as they are only placeholders and don't need to be in the actual implementations IMO.

2022-11-02 06:46 UTC, moonbeamcelery commented on app/src/main/kotlin/dev/patrickgold/florisboard/ime/core/Subtype.kt
> +    val suggestion: String = HanShapeBasedLanguageProvider.ProviderId,
Please see [this downstream PR](https://github.com/Waelwindows/florisboard/pull/4) for a quick-and-dirty update of

- exposing selecting nlpProviders to settings and changing default back to Latin
- polished the Chinese preset
- support for more Chinese input methods
- bigger (TM) app size (+150%)

2022-11-02 07:16 UTC, moonbeamcelery commented
Hi Patrickgold, thank you for your feedback!

After some of the fixes I've worked on, some issues remain:
- Need to force suggestion on (and preferrably force smartbar on) when HanShapeBasedLanguageProvider is used, or it will not work and turn away users.
- Features from [another PR](https://github.com/Waelwindows/florisboard/pull/4/commits) especially dfa698e111cdbe4e252623a75f3362d1ea8f74d8 (define composeable characters) and dfa698e111cdbe4e252623a75f3362d1ea8f74d8 (fix catching error when table is not found)
- (I will test more and add here if I can find anything)

Nice-to-haves:
- Support for custom code-word pairs. The tables are not up to date with the newest Internet slang.

By the way, please note that shape-based input methods that we are working to support are not widely used in areas such as mainland China, where phonetic-based ones are much more popular.

2022-11-02 12:52 UTC, Waelwindows commented
> Also thanks for providing a NIX config file, even though I have no way of actually testing it it may be useful for other users who build this project in a NIX environment.

Didn't mean to add those in this PR as I was hoping to get it working _properly_ first without hacks. I'll remove them soon

2022-11-17 08:15 UTC, moonbeamcelery commented
Update from the other PR: [f4c2328](https://github.com/florisboard/florisboard/pull/2093/commits/f4c232878dbbf245badaa97c265f26efa02f2848) adds forced suggestion on for HanShapeBased subtypes.

On another note, I have been daily driving this (merged with #2093) and did not find much issue. However, I have not extensively tested the subtype setup (and language pack import) process.

2022-12-10 22:01 UTC, moonbeamcelery commented
Some usability issues I found over the past weeks:

1. When I type very quickly, it is very easy for the last letter to not be included in the suggestions (for both the new Chinese input and the original English subtype). This is weird because when I compiled the app in another machine, this issue disappears. I am not certain this is an issue that need to be fixed. If anyone compiles this, please check if this is an issue.
2. The CJK layout is not very friendly to Chinese input, with parentheses hidden behind two taps and a long press, and comma and period hidden behind a long press. @Waelwindows do you mind if I make some changes to the CJK keyboard (as another PR)? I'm thinking of at least adding the parentheses as a popup for the character keyboard, and merge the postal symbol with the # symbol.

2022-12-11 17:35 UTC, Waelwindows commented
>     2. The CJK layout is not very friendly to Chinese input, with parentheses hidden behind two taps and a long press, and comma and period hidden behind a long press. @Waelwindows do you mind if I make some changes to the CJK keyboard (as another PR)? I'm thinking of at least adding the parentheses as a popup for the character keyboard, and merge the postal symbol with the # symbol.

You are free to make any changes you like. However, the pop-ups can be easily swtiched over to the regular ones in the subtype configuration within FlorisBoard.

2022-12-12 06:18 UTC, moonbeamcelery commented
> > ```
> > 2. The CJK layout is not very friendly to Chinese input, with parentheses hidden behind two taps and a long press, and comma and period hidden behind a long press. @Waelwindows do you mind if I make some changes to the CJK keyboard (as another PR)? I'm thinking of at least adding the parentheses as a popup for the character keyboard, and merge the postal symbol with the # symbol.
> > ```
> 
> You are free to make any changes you like. However, the pop-ups can be easily swtiched over to the regular ones in the subtype configuration within FlorisBoard.

Thanks! The regular one does not have full-width punctuation (period, comma, parentheses), though.

2022-12-31 12:54 UTC, patrickgold requested changes
As mentioned yesterday in the Eelement group chat I am now thoroughly reviewing this PR so we can finally begin to merge in your PR and all sub-PRs after that :)

I tested out the Chinese (RC) subtype preset on one of my testing phones and the layout and its suggestions are butter-smooth, I didn't experience any lag and the typing experience feels very good (as far as I can tell as a non-Chinese speaking person).

About the sqlite3 database: what exactly is the license of this database? (I just need to ensure I don't accidentally merge something that's not allowed to be in an Apache-2.0 codebase)

As for the extension system and how it is utilized for Chinese, there's a lot of improvement to be done here but like we currently discuss in the Element group chat that's a thing we will need to discuss more thoroughly in general (the "language pack" idea) and should not be a blocking point for this PR to be merged.

One thing about the sub-PRs to this PR, there's [this](https://github.com/Waelwindows/florisboard/pull/4) PR from @moonbeamcelery provides a lot of fixes and improvements to this PR, would it be possible for you @Waelwindows that you first merge in that PR into your branch, update your PR here so I have the proper code diff to review in one place? That would make it a lot easier for me to review and also I would not merge in code that for instance forces the language provider to the HanShapeBased one.

And of course thanks a lot for both of yours effort to implement such a big feature and provide so much code to this project, that's very much appreciated :)

2022-12-31 12:54 UTC, patrickgold commented on flake.nix
> +{
IIRC you said the nix config doesn't work correctly and you want to remove it, is this info still relevant or does this nix config work now?

2022-12-31 17:31 UTC, moonbeamcelery commented
> About the sqlite3 database: what exactly is the license of this database? (I just need to ensure I don't accidentally merge something that's not allowed to be in an Apache-2.0 codebase)

The sqlite3 is derived from ibus' tables, which are GPL3. [The other PR](https://github.com/Waelwindows/florisboard/pull/4) changes it to base on the one from fcitx, which claims that the three tables included are in public domain.

2023-01-01 09:59 UTC, patrickgold commented
> The sqlite3 is derived from ibus' tables, which are GPL3. https://github.com/Waelwindows/florisboard/pull/4 changes it to base on the one from fcitx, which claims that the three tables included are in public domain

Ah right I remember know we once talked about this. Then it is even more important that your sub-PR is merged into this PR first :)

2023-01-07 23:52 UTC, moonbeamcelery commented
Thanks for merging! Posting remaining issues (or future work) here:

- `extensionManager.languagePacks.observeForever` does not work in `HanShapeBasedLanguageProvider` because thread usage, and a hacky workaround is used
- The extension files including the huge tables are still copied each time `HanShapeBasedLanguageProvider.create()` is called.
- Polishing the new `LANGUAGEPACK.md` page for introducing users to language packs
- Decoupling of the language extension implementation with HanShapeBased, and support including layouts etc. in it.
- Potential idea to fix the half-width/full-width confusion: change the half-width/full-width toggle to have three states: all half, all full, full for punctuation only.

2023-01-08 00:04 UTC, moonbeamcelery commented on LANGUAGEPACKS.md
> +- [Chinese / 中文](#chinese--)
This link doesn't work :joy:

2023-01-08 22:45 UTC, patrickgold requested changes
Thanks a lot for merging in moonbeamcelery's PR, this brought us closer to merging in this PR into master :)

I've now had an extensive look at the changes, first trying it out on my testing device and must say that I am really impressed by both of your's work, it works really well and as far as I could tell the default suggestion behavior of the normal Latin-script languages is untouched.

I also had a look at the language pack proposal. As we've discussed previously in the Matrix group chat the language pack feature is a very important design decision for this project (and its extensibility in the future) so I cannot say for sure that it will stay as you've implemented it atm, however the draft itself is very well written. I will make a separate PR for this in the future were I will present my own draft and then we can discuss and fine-tune this idea and move the Chinese language packs into the new version.

There's probably still some cleanup to do in the code base, however for now I think it is pretty well written (also we have to consider that pretty much everything surrounding the NLP stuff is experimental so I think the best move is to merge this PR in, then the other ones and later on when more stuff is final we can do cleanup).

For the specific issues I saw I added a comment to each of those separately.

Also because it seems like my last review comment has gone under, is the NIX config in this PR obsolete or does it work?

2023-01-08 22:45 UTC, patrickgold commented on LANGUAGEPACKS.md
> +Third-party license: [https://github.com/fcitx/fcitx5-table-extra/blob/master/LICENSES/GPL-3.0-or-later.txt]
We only use the data tables from the fcitx repository, or did I miss something? As the code itself is GPL-3 licensed which cannot be used in this repo due to licensing issues. If this is the case we can replace this paragraph with something like "The data tables are from the fcitx repository and are available as public domain."

2023-01-08 22:45 UTC, patrickgold commented on app/src/main/assets/ime/languagepack/org.florisboard.languagepack/extension.json
> +  ]
Is there any specific reason why exactly these two languages are in the default language pack? Or was this just to try it out how it looks for the default language pack?

2023-01-08 22:45 UTC, patrickgold commented on app/src/main/kotlin/dev/patrickgold/florisboard/ime/core/Subtype.kt
> +import dev.patrickgold.florisboard.ime.nlp.han.HanShapeBasedLanguageProvider
Does this import have any use (As no other code was changed in this file)?

2023-01-08 23:01 UTC, moonbeamcelery commented on LANGUAGEPACKS.md
> +Third-party license: [https://github.com/fcitx/fcitx5-table-extra/blob/master/LICENSES/GPL-3.0-or-later.txt]
Here are the details:

- All tables are now from the fcitx repo. We do not include any of their code. The python script that processes their public domain tables are in the PR though.
- The fcitx repo claims all their tables are in the public domain, but only lists references as proof for three (zhengma, cangjie, boshiamy) out of the many tables.
- This pr now includes zhengma, cangjie, and quickclassic (which is a variant of cangjie) in the main repo, because I thought of them as "safe". Maybe I should remove quickclassic as well and move that to the extended pack, and maybe include boshiamy in the main repo.
- The lines you commented on are talking about the extended pack, which is not included in the PR so that they can be hosted elsewhere with a separate license. The files for that extended pack is [here](https://drive.proton.me/urls/QJR03A7QWR#bPKQyz2ZaqZv).

2023-01-08 23:09 UTC, patrickgold commented on LANGUAGEPACKS.md
> +- [Chinese / 中文](#chinese--)
Just had a look at the generated Markdown and GitHub actually uses the Chinese symbols in the href target:
![image](https://user-images.githubusercontent.com/19412843/211223624-9b22ad19-e40e-4112-88a2-30cb14be0da8.png)

So if you change the link location like in the suggested change below it should work.

```suggestion
- [Chinese / 中文](#chinese--中文)
```

2023-01-08 23:10 UTC, moonbeamcelery commented on app/src/main/assets/ime/languagepack/org.florisboard.languagepack/extension.json
> +  ]
These "languages" are present in the subtype presets, but as of now do not exist in the language selection screen. That means to get these subtypes, you have to use the presets to fill these fields. And once you swap them out, you cannot choose them again and have to delete and re-add using the preset.

Adding these makes it possible to select them from the screen (see [this](https://github.com/florisboard/florisboard/pull/2054/files/35863c0c98967678060da95252936c0dd2ebb7c8#diff-38917653f0bade843930ec67db1d14885b5e217fa70ede7273e615f7f1864d83R136) and [this](https://github.com/florisboard/florisboard/pull/2054/files/35863c0c98967678060da95252936c0dd2ebb7c8#diff-1550e324febcaa10aab9700e41a9b45252b6e0c9054af1c82eec0e3203bdc495R70)). Although the main purpose of `extendedAvailableLocales` is so people can select out of the many added Chinese IMEs.

2023-01-08 23:12 UTC, moonbeamcelery commented on app/src/main/kotlin/dev/patrickgold/florisboard/ime/core/Subtype.kt
> +import dev.patrickgold.florisboard.ime.nlp.han.HanShapeBasedLanguageProvider
Apologies, but those are automatically added over many commits, and may have been left unused after some code refactoring. There are [many unused imports like this](https://github.com/florisboard/florisboard/pull/2054/files/35863c0c98967678060da95252936c0dd2ebb7c8#diff-c57e71f7424bee4c416346f7b092da5eaa977a28c82ba4cb37198439e16f3769R48-R50).

2023-01-08 23:16 UTC, patrickgold commented on LANGUAGEPACKS.md
> +Third-party license: [https://github.com/fcitx/fcitx5-table-extra/blob/master/LICENSES/GPL-3.0-or-later.txt]
Thanks a lot for the details, now this is a lot clearer for me.

> This pr now includes zhengma, cangjie, and quickclassic (which is a variant of cangjie) in the main repo, because I thought of them as "safe". Maybe I should remove quickclassic as well and move that to the extended pack, and maybe include boshiamy in the main repo.

I just had a look at the fcitx repo and yeah difficult to say, but I think the safe licensing-way would be to swap quickclassic with boshiamy if it isn't too much work for you.

> The lines you commented on are talking about the extended pack

Aaah I see, I literally can't read properly xD

2023-01-08 23:17 UTC, patrickgold commented on app/src/main/kotlin/dev/patrickgold/florisboard/ime/core/Subtype.kt
> +import dev.patrickgold.florisboard.ime.nlp.han.HanShapeBasedLanguageProvider
Ah ok then I think I will just remove them all at once some time in the future with the auto-cleanup feature built into Android Studio, this way we can focus on the important things :)

2023-01-08 23:20 UTC, patrickgold commented on app/src/main/assets/ime/languagepack/org.florisboard.languagepack/extension.json
> +  ]
Ah I see then for now we'll leave it like that and I'll work with it in the language pack design PR from my side.

2023-01-09 05:45 UTC, moonbeamcelery commented on LANGUAGEPACKS.md
> +Third-party license: [https://github.com/fcitx/fcitx5-table-extra/blob/master/LICENSES/GPL-3.0-or-later.txt]
Added fix [here](https://github.com/Waelwindows/florisboard/pull/5).

2023-01-10 23:02 UTC, Waelwindows commented on flake.nix
> +{
It works but you need to suffix every gradle command with `$GRADLE_OPT`, I'll look into fixing this in a different PR.

2023-01-10 23:59 UTC, Waelwindows commented
I've noticed there's quite some lag on the `Select Language` screen when searching. Should we fix that before we merge this or can we move it to another PR?

2023-01-11 00:57 UTC, moonbeamcelery commented
I think the select language screen always had that lag, at least it does on the latest beta version.

2023-01-13 16:06 UTC, patrickgold commented on app/src/main/assets/ime/keyboard/org.florisboard.localization/extension.json
> +
I'm currently not at home so cannot test it on my testing device but it seems that the JSON syntax got messed up while rebasing. (Will properly review the latest changes later)

```suggestion
    },
```

2023-01-13 20:11 UTC, patrickgold requested changes
Re-reviewed your changes and while rebasing it seems like 2 ending curly braces in the localization json have been lost (see suggested change).

Besides that everything is still fine. The lag for the language screen is indeed there however this was already present before your PR, thus not introduced by your code.

So from my side this PR is mergeable once the extension.json file is fixed.

2023-01-14 01:47 UTC, Waelwindows commented on app/src/main/assets/ime/keyboard/org.florisboard.localization/extension.json
> +
That's probably why subtype presets broke :thinking:

2023-01-14 02:54 UTC, moonbeamcelery commented
Thank you for all the work! This feature would be very useful for me personally.
@patrickgold : do you want to consider cleaning the history of the PR to leave out the historical versions of the tables?

2023-01-14 09:46 UTC, Waelwindows commented
> do you want to consider cleaning the history of the PR to leave out the historical versions of the tables?

I don't think it's gonna be a problem since it'll be merged / squashed not rebased IIRC

2023-01-15 16:20 UTC, patrickgold approved these changes
Thank you for fixing the issue in the extension json file.

From my side this PR is now fully ready to be merged. As for the commit history, I will squash merge in the changes, so the history is irrelevant.

Again thanks y'all for your hard work and sorry again that this PR got delayed so much from my side!

2023-01-15 16:22 UTC, merged