Add support for Asturian
florisboard/florisboard pull request #2062
Opened 2022-09-08 16:21 UTC by softastur

All steps to add a new layout, as described in https://github.com/florisboard/florisboard/blob/master/CONTRIBUTING.md, have been completed so Asturian layout should be ready to use.

2022-12-23 17:18 UTC, patrickgold requested changes
Hey,

first of all I am very sorry for not reviewing your pull request for so long, last few months have been pretty stressful for me and thus I haven't really had much time for FlorisBoard, hope you can understand!

I've reviewed your changes and tested your layout on-device and it looks good, however there are two things that need to be changed (see attached review comments on the specifics). Once they are fixed I will happily merge in your changes and release them with the next alpha release :)

2022-12-23 17:18 UTC, patrickgold commented on app/src/main/assets/ime/keyboard/org.florisboard.layouts/layouts/characters/asturian.json
> +[
This file is identical to qwerty.json, and in fact in the default subtype you use QWERTY directly, so I suppose we can remove this json file as it is unused.

2022-12-23 17:18 UTC, patrickgold commented on app/src/main/assets/ime/keyboard/org.florisboard.localization/extension.json
> +    },
The last comma after the curly brace is invalid JSON and causes a parse error, removing it fixes the problem.
 
```suggestion
    }
```

2023-01-02 22:59 UTC, closed without merging

2023-01-02 23:09 UTC, softastur commented
I've just screw things up and all changes were deleted when trying to sync repos. I will create a new PR in a few minutes containing all fixes and suggestions............