Add ЈЦУКЕН interslavic keyboard layout
florisboard/florisboard pull request #2354
Opened 2023-12-31 16:18 UTC by victorbnl

Closes #1633

2023-12-31 16:34 UTC, victorbnl commented
I couldn’t figure out where to add the layout in `extension.json` because the first half of the list seems to be sorted alphabetically, but then the order seems random. So I ended up adding it to the end of the list. But feel free to tell me if I should move it.

2024-06-20 09:03 UTC, kuroya2mouse commented
I think that there is no need for a layout for Interslavic language. It would really be better to add the Interslavic language itself so that there are suggestions on top of the letters like with Czech language + QWERTY/Colemak layout.

![screen](https://github.com/florisboard/florisboard/assets/108447847/525df08f-24d5-47ec-8652-810119742b63)

2024-07-08 01:36 UTC, patrickgold approved these changes

2024-07-08 01:37 UTC, merged

2024-08-15 09:15 UTC, eqoffical requested changes

2024-08-15 09:15 UTC, eqoffical commented on app/src/main/assets/ime/keyboard/org.florisboard.layouts/layouts/characters/jcuken_interslavic.json
> +[
the "Д" (or "D") letter is missing