[Meta]: Switch to issue forms
florisboard/florisboard pull request #2366
Opened 2024-01-11 01:14 UTC by lm41

This pull request changes the issue templates to issue forms to avoid "unnecessary" issues and to make it easier for the user to create an issue. I know that the issue forms are still in beta, but I think they have been around long enough to be considered stable.

2024-01-11 23:30 UTC, patrickgold requested changes
Thanks for the issue templates!

I completely forgot that GitHub had issue forms, also really strange that the app still not supports them. But yeah in general I think using them is the way to go. Had a look at your templates and they look good.

As for the bracket tags in the title: do you think they add good use? I fear that they may clutter the titles, as we already have the labels like bug and proposal. Not sure yet how I should feel about them yet, although in general I don't have anything against them.

2024-01-11 23:30 UTC, patrickgold commented on .github/ISSUE_TEMPLATE/feature_request.yml
> +title: "[FEAT]: "
To keep the bracket tagging consistent with Bug and Crash we should titlecase Feat instead of uppercasing it.

```suggestion
title: "[Feat]: "
```

2024-01-11 23:33 UTC, lm41 commented on .github/ISSUE_TEMPLATE/feature_request.yml
> +title: "[FEAT]: "
It's totally up to you if you want the brackets in the title. But you are right that we have labels for that ¯\_(ツ)_/¯

2024-01-11 23:39 UTC, patrickgold commented on .github/ISSUE_TEMPLATE/feature_request.yml
> +title: "[FEAT]: "
I just had some thoughts about this and think that omitting them is the cleaner way to go, especially as everything else mostly didn't carry bracket tags either and it worked quite well

2024-01-12 07:45 UTC, patrickgold approved these changes
Looks good to me now. Merging in.

2024-01-12 07:46 UTC, merged

2024-01-12 07:48 UTC, patrickgold commented
Ok for the GitHub app I just tried it out it doesn't support them  but at least it redirects to a browser then, so there's no option that users can create issues without the template anymore.