Refine Clipboard Suggestion Validation to Prevent Empty and Invalid Items
florisboard/florisboard pull request #2387
Opened 2024-01-24 20:46 UTC by snaik20

### Summary:
- This PR addresses an issue where empty or invalid clipboard items that could lead to incorrect suggestions.
- It introduces validation logic to ensure only meaningful content is suggested.

### Context:
- The issue was observed when apps like KDE Connect added empty or special character-only items to the clipboard.
- The `ClipboardSuggestionProvider` previously lacked validation for such cases.

### Changes:
- Added validation for empty clipboard items.
- Enhanced validation to handle special characters (newlines, tabs).
- Introduced private methods and constants for improved readability and maintainability.

Fixes #2386

2024-02-04 18:15 UTC, patrickgold requested changes
Thanks a lot for your changes!

I have reviewed your code and in general like your idea. However there's a better and more streamlined version to do blank str matching using regex, see the suggested changes. `\s` matches quite a few blank characters and avoids us hard-coding what a blank character is, see the [Java docs for Pattern](https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html)

2024-02-04 18:15 UTC, patrickgold commented on app/src/main/kotlin/dev/patrickgold/florisboard/ime/nlp/NlpManager.kt
> +private const val SPACE = ""
```suggestion
private const val BLANK_STR_REGEX = Regex("^\\s*$")
```

2024-02-04 18:15 UTC, patrickgold commented on app/src/main/kotlin/dev/patrickgold/florisboard/ime/nlp/NlpManager.kt
> +                    && currentItem.text?.replace(NEW_LINE, SPACE)?.replace(TAB, SPACE)?.isBlank() == false
```suggestion
                    && !BLANK_STR_REGEX.matches(currentItem.text ?: "")
```

2024-02-04 20:00 UTC, snaik20 commented on app/src/main/kotlin/dev/patrickgold/florisboard/ime/nlp/NlpManager.kt
> +private const val SPACE = ""
Done.

2024-02-04 20:01 UTC, snaik20 commented on app/src/main/kotlin/dev/patrickgold/florisboard/ime/nlp/NlpManager.kt
> +                    && currentItem.text?.replace(NEW_LINE, SPACE)?.replace(TAB, SPACE)?.isBlank() == false
Done

2024-02-04 20:01 UTC, snaik20 commented
> Thanks a lot for your changes!
> 
> I have reviewed your code and in general like your idea. However there's a better and more streamlined version to do blank str matching using regex, see the suggested changes. `\s` matches quite a few blank characters and avoids us hard-coding what a blank character is, see the [Java docs for Pattern](https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html)

Sounds great. Verified the new changes and updated PR.

2024-02-06 03:54 UTC, patrickgold approved these changes
Thanks a lot for your changes, now everything looks good, merging in!

2024-02-06 03:54 UTC, merged