Fix #2309, #2134 and some deprecation warnings
florisboard/florisboard pull request #2388
Opened 2024-01-24 20:54 UTC by lm41

2024-02-07 21:07 UTC, patrickgold requested changes
Thanks a lot for the changes, really appreciate it!

I've reviewed the code and tested out each issue if it is fixed. My feedback:

1) #2309 is fixed, recent emojis aren't showing up anymore when the device is locked. Code for that also looks clean
2) #2134 is fixed but introduced a new crash, see the specific review comment for details
3) #2112 I don't like the UX of the import, can you add at least a toast message with "Added to clipboard history" or "Failed to add because XYZ"? Also the import itself is extremely buggy, e.g. from the OnePlus camera import fails, from ente photos it works flawlessly (same image btw).
4) #2378 is confirmed fixed, however you allow passage in the setup screen even if the user denies the permission, is this intended?

Also the usual formatting nitpicks as single comments :)

2024-02-07 21:07 UTC, patrickgold commented on app/src/main/AndroidManifest.xml
> +    <!-- Permission needed to create notifications on devices running android 13+-->
```suggestion
    <!-- Permission needed to create notifications on devices running Android 13+ -->
```

(formatting nitpick)

2024-02-07 21:07 UTC, patrickgold commented on app/src/main/kotlin/dev/patrickgold/florisboard/app/FlorisAppActivity.kt
> +
That check does not work or the redirect fails, either way if I disable notifications after setup the settings never complains about that anymore

2024-02-07 22:21 UTC, lm41 commented on app/src/main/kotlin/dev/patrickgold/florisboard/app/FlorisAppActivity.kt
> +
This is intended behavior. We can no longer request permission after it has been rejected anyway
https://developer.android.com/training/permissions/requesting#handle-denial
If the user decides to denie a permission he has to take the consequences. He can always grant the permission in the android app settings anyway. 
```
At the same time, your app should respect the user's decision to deny a permission. Starting in Android 11 (API level 30), if the user taps Deny for a specific permission more than once during your app's lifetime of installation on a device, the user doesn't see the system permissions dialog if your app requests that permission again. The user's action implies "don't ask again." On previous versions, users saw the system permissions dialog each time your app requested a permission, unless they had previously selected a "don't ask again" checkbox or option.
```

Now to the check. This is primarily there to bring the permission / the new grant notification step back into the setup screen for devices that are android 13+ and have not yet seen it. So for people who have already installed the app in a beta, who have already completed the setup, but have not yet granted the permission because it was not implemented before.

2024-02-07 22:31 UTC, lm41 commented
I cannot reproduce the buggy behavior of the share to florisboard feature. It works flawlessly on my Pixel (GrapheneOS Android 14).

2024-02-07 23:04 UTC, patrickgold commented on app/src/main/kotlin/dev/patrickgold/florisboard/app/FlorisAppActivity.kt
> +
Ah I see thanks a lot for the explanation, didn't know that specific detail about permissions. Also now that check makes sense.

2024-02-07 23:05 UTC, patrickgold commented
> I cannot reproduce the buggy behavior of the share to florisboard feature. It works flawlessly on my Pixel (GrapheneOS Android 14).

It could also be buggy behavior of the OnePlus camera app, will check if I find other apps to reproduce this on.

2024-02-07 23:21 UTC, patrickgold commented
An idea for the copy to clipboard activity UX: instead of auto closing it you could also make the activity transparent and slide a small dialog bottom sheet in, which shows the copied image, a text like "added to FlorisBoard clipboard" (or in an error case error details) and a button to close (additionally to swipe down). This way we can prevent visual artifacts, because if the system is quite busy the activity can cause a short black screen flash.

2024-02-07 23:40 UTC, lm41 commented
> An idea for the copy to clipboard activity UX: instead of auto closing it you could also make the activity transparent and slide a small dialog bottom sheet in, which shows the copied image

I like this idea. I will try something like that. 
I hadn't even thought about the possibility of a blakcscreen, as I don't think this occurs with my hardware. I really need an older device on which I can test something like this :/

2024-02-08 11:52 UTC, patrickgold commented
> I really need an older device on which I can test something like this :/

an emulator with arm architecture on x86 hardware is enough :)

2024-02-29 15:24 UTC, patrickgold requested changes
Thanks a lot for the changes! Your code looks really good now, just some small formatting nitpickings and then we can merge in the changes!

2024-02-29 15:24 UTC, patrickgold commented on app/src/main/res/values/themes.xml
> +        <item name="android:backgroundDimEnabled">false</item>-->
Those can be removed, was an artifact of me debugging your theme

```suggestion
```

2024-02-29 15:24 UTC, patrickgold commented on app/src/main/kotlin/dev/patrickgold/florisboard/FlorisCopyToClipboardActivity.kt
> +
```suggestion
```

(formatting nitpicking)

2024-02-29 15:25 UTC, patrickgold commented
Also should I fix the merge conflicts upon merging or do you do it?

2024-02-29 15:36 UTC, patrickgold approved these changes
Perfect thanks for fixing, will merge in the changes once the pipeline is finished!

2024-02-29 15:41 UTC, merged