Switch to ImageVector icons
florisboard/florisboard pull request #2432
Opened 2024-03-29 11:56 UTC by lm41

2024-03-29 14:07 UTC, patrickgold commented on app/src/main/kotlin/dev/patrickgold/florisboard/ime/keyboard/ComputingEvaluator.kt
> +                ImageVector.vectorResource(theme = null, resId = R.drawable.ic_keyboard_kana_switcher_kata, res = this.context()?.resources!!)
if we can construct an ImageVector from a drawable res id that easily could we not obsolete jetIcon in jetpref and make a shorthand function?

E.g.
```kotlin
fun Context.vectorResource(@DrawableRes id: Int): ImageVector {
    val theme = null // could be inferred from context receiver probably
    return ImageVector.vectorResource(theme = theme, resId = id, res = this.resources)
}

@Composable
inline fun vectorResource(@DrawableRes id: Int): ImageVector {
    val context = LocalContext.current
    return context.vectorResource(id)
}
```

Then in all preference composables just accept an ImageVector. If you like that idea I would suggest completely removing drawable id support in `jetpref` (just accept an `icon: ImageVector?` param) and adding this utility to the `lib.compose` module.

2024-03-29 17:55 UTC, lm41 commented on app/src/main/kotlin/dev/patrickgold/florisboard/ime/keyboard/ComputingEvaluator.kt
> +                ImageVector.vectorResource(theme = null, resId = R.drawable.ic_keyboard_kana_switcher_kata, res = this.context()?.resources!!)
We could, but I would include the shorthand function in the jetpref library. (So that if others want to use jetpref they don't always have to implement it themselves)

2024-03-30 01:28 UTC, patrickgold commented on app/src/main/kotlin/dev/patrickgold/florisboard/ime/keyboard/ComputingEvaluator.kt
> +                ImageVector.vectorResource(theme = null, resId = R.drawable.ic_keyboard_kana_switcher_kata, res = this.context()?.resources!!)
Ok yeah then lets do it this way

2024-04-05 17:34 UTC, lm41 commented on gradle/libs.versions.toml
> +patrickgold-jetpref = "20240328T224800Z-SNAPSHOT"
i have now added the review suggestions and am now waiting for a release of jetpref.

2024-04-06 10:09 UTC, patrickgold commented on gradle/libs.versions.toml
> +patrickgold-jetpref = "20240328T224800Z-SNAPSHOT"
I made a new [release](https://github.com/patrickgold/jetpref/releases/tag/0.1.0-rc02)

2024-04-07 09:27 UTC, patrickgold requested changes
Thanks a lot for the changes! Tested them and everything checks out fine, only 2 small artifacts from testing need to be changed and then it is ready for merging into master.

2024-04-07 09:27 UTC, patrickgold commented on settings.gradle.kts
> +        maven("https://s01.oss.sonatype.org/content/repositories/snapshots")
needs to be recommented again
```suggestion
        // maven("https://s01.oss.sonatype.org/content/repositories/snapshots")
```

2024-04-07 09:27 UTC, patrickgold commented on app/src/main/kotlin/dev/patrickgold/florisboard/app/settings/about/AboutScreen.kt
> +        //TODO: Wait until https://github.com/patrickgold/jetpref/pull/2 is merged to update the preferences
```suggestion
```

2024-04-07 11:40 UTC, patrickgold approved these changes

2024-04-07 11:40 UTC, merged