WIP: Add clipboard history to backup.
florisboard/florisboard pull request #2458
Opened 2024-04-24 00:23 UTC by lm41

Closes: #1944

2024-04-26 09:26 UTC, patrickgold requested changes
Thanks a lot for the changes!

In general a good addition, however if we allow clipboard backup we should also include media items, else I can already see users complaining that this is missing. In fact the backup of media items and its difficulty was the primary reason why I didn't touch this feature yet.

But other than that the backup of text items is cleanly implemented!

2024-04-26 09:26 UTC, patrickgold commented on app/src/main/kotlin/dev/patrickgold/florisboard/lib/util/UriSerializer.kt
I'd personally opt for this serializer to be placed in lib.compose, as it is a direct "extension" of functionality of a system class

2024-04-26 09:28 UTC, patrickgold commented
In terms of the weird app state I'll investigate later on if I can reproduce this and if I find a fix for it.

2024-04-27 10:41 UTC, patrickgold requested changes
Thanks a lot for the changes!

I reviewed your code and tested the functionality, please see the comments on what I found.

A general thing: Should the clipboard history be exportable when it is disabled in the prefs? I am currently torn apart if it should or shouldn't...

In terms of weird app state could you elaborate more on what you mean by that or how to reproduce it? On my quick testing I couldn't really see it.

2024-04-27 10:41 UTC, patrickgold commented on app/src/main/kotlin/dev/patrickgold/florisboard/ime/clipboard/provider/ClipboardMediaProvider.kt
> +import dev.patrickgold.florisboard.lib.io.FsDir
that import is probably an artifact right?

2024-04-27 10:41 UTC, patrickgold commented on app/src/main/kotlin/dev/patrickgold/florisboard/ime/clipboard/provider/ClipboardFileStorage.kt
> +
```suggestion
```

(format nitpick)

2024-04-27 10:41 UTC, patrickgold commented on app/src/main/kotlin/dev/patrickgold/florisboard/ime/clipboard/provider/ClipboardDatabase.kt
> +@Serializable
I was about to nitpick that the order of annotations vary for ClipboardItem and ClipboardFilesInfo until I did a quick search and noticed there is 0 consistency from my added code either... I'd just suggest that in the same file we have consistent ordering.

2024-04-27 10:41 UTC, patrickgold commented on app/src/main/kotlin/dev/patrickgold/florisboard/ime/clipboard/ClipboardManager.kt
> +    fun restoreHistory(shouldReset: Boolean, items: List<ClipboardItem>) {
Flags of functions are usually placed after the main argument, in that case I'd suggest having `items` as the first arg and `shouldReset` as the second

2024-04-27 10:41 UTC, patrickgold commented on app/src/main/kotlin/dev/patrickgold/florisboard/app/settings/advanced/BackupScreen.kt
> +        var clipboardData by mutableStateOf(true)
Here the question arises should clipboard data automatically be marked for backup? Clipboard data is the first section in this screen that backs up sensitive information, so if the user doesn't notice that it is checked and backs up the zip to an unencrypted location they could accidentally leak private information. However I am not sure and open to other opinions here.

2024-04-27 10:41 UTC, patrickgold commented on app/src/main/kotlin/dev/patrickgold/florisboard/app/settings/advanced/BackupScreen.kt
> +        )
Technically from UI design perspective this should be a [TriStateCheckbox](https://developer.android.com/reference/kotlin/androidx/compose/material/package-summary#TriStateCheckbox(androidx.compose.ui.state.ToggleableState,kotlin.Function0,androidx.compose.ui.Modifier,kotlin.Boolean,androidx.compose.foundation.interaction.MutableInteractionSource,androidx.compose.material.CheckboxColors)), because if only some children are selected the checkbox should reflect that the clipboard is only partially backed up. However I don't mind if we keep it the current way.

2024-04-27 10:41 UTC, patrickgold commented on app/src/main/kotlin/dev/patrickgold/florisboard/app/settings/advanced/BackupScreen.kt
> +            text = stringRes(R.string.backup_and_restore__back_up__files_clipboard_history__clipboard_text_items),
```suggestion
            text = stringRes(R.string.backup_and_restore__back_up__files_clipboard_history__clipboard_image_items),
```

(you used the incorrect string, probably due to copy/paste)

2024-04-27 10:41 UTC, patrickgold commented on app/src/main/kotlin/dev/patrickgold/florisboard/app/settings/advanced/BackupScreen.kt
> +            text = stringRes(R.string.backup_and_restore__back_up__files_clipboard_history__clipboard_text_items),
```suggestion
            text = stringRes(R.string.backup_and_restore__back_up__files_clipboard_history__clipboard_video_items),
```

(you used the incorrect string, probably due to copy/paste)

2024-04-27 10:41 UTC, patrickgold commented on app/src/main/res/values/strings.xml
> +    <string name="backup_and_restore__back_up__files_clipboard_history">Clipboard History</string>
```suggestion
    <string name="backup_and_restore__back_up__files_clipboard_history">Clipboard history</string>
```

(consistency with other parts of the UI)

2024-04-27 10:41 UTC, patrickgold commented on app/src/main/res/values/strings.xml
> +    <string name="backup_and_restore__back_up__files_clipboard_history__clipboard_text_items">Text Items</string>
```suggestion
    <string name="backup_and_restore__back_up__files_clipboard_history__clipboard_text_items">Text items</string>
```

(consistency with other parts of the UI)

2024-04-27 10:49 UTC, lm41 commented on app/src/main/kotlin/dev/patrickgold/florisboard/app/settings/advanced/BackupScreen.kt
> +        var clipboardData by mutableStateOf(true)
You're right, it's more from testing that I didn't always have to check it manually

2024-04-27 10:49 UTC, lm41 commented on app/src/main/kotlin/dev/patrickgold/florisboard/app/settings/advanced/BackupScreen.kt
> +            text = stringRes(R.string.backup_and_restore__back_up__files_clipboard_history__clipboard_text_items),
Oops

2024-04-29 19:14 UTC, merged