Material3 migration
florisboard/florisboard pull request #2467
Opened 2024-05-04 14:21 UTC by lm41

- [ ] Use constistent colors
- [ ]

2024-05-05 11:32 UTC, patrickgold requested changes
Thanks a lot for the changes! Generally the new UI looks pretty solid, we may still need some minor color scheme adjustments but apart from that everything looks good.

I've reviewed the code changes and have some requests and nitpicks.

2024-05-05 11:32 UTC, patrickgold commented on app/src/main/kotlin/dev/patrickgold/florisboard/app/settings/about/ThirdPartyLicensesScreen.kt
> +                dialogConfirmButtonColor = MaterialTheme.colorScheme.primary
```suggestion
                dialogConfirmButtonColor = MaterialTheme.colorScheme.primary,
```

(nitpick)

2024-05-05 11:32 UTC, patrickgold commented on app/src/main/kotlin/dev/patrickgold/florisboard/app/settings/advanced/AdvancedScreen.kt
> +            }
```suggestion
            },
```

(nitpick)

2024-05-05 11:32 UTC, patrickgold commented on app/src/main/kotlin/dev/patrickgold/florisboard/lib/compose/FlorisCards.kt
> +            disabledContentColor = contentColor
```suggestion
            disabledContentColor = contentColor,
```

(nitpick)

2024-05-05 11:32 UTC, patrickgold commented on app/src/main/kotlin/dev/patrickgold/florisboard/lib/compose/FlorisChip.kt
> +    )
```suggestion
        }
    )
```

2024-05-05 11:32 UTC, patrickgold commented on gradle/libs.versions.toml
> +patrickgold-jetpref = "20240504T230200Z-SNAPSHOT"
We need a proper jetpref release before merging in

2024-05-05 11:32 UTC, patrickgold commented on settings.gradle.kts
> +        maven("https://s01.oss.sonatype.org/content/repositories/snapshots")
before merge comment in again

2024-05-05 11:32 UTC, patrickgold commented on app/src/main/kotlin/dev/patrickgold/florisboard/lib/compose/FlorisScreen.kt
I have identified the issue regarding the scrollbar calculating too much, it was applied to early, which was always an error but somehow still worked in the old UI...

Please replace the Scaffold code in Render() with this:
```kotlin
        Scaffold(
            topBar = { FlorisAppBar(title, navigationIcon.takeIf { navigationIconVisible }, actions) },
            bottomBar = bottomBar,
            floatingActionButton = fab,
        ) { innerPadding ->
            val scrollModifier = if (scrollable) {
                Modifier.florisVerticalScroll()
            } else {
                Modifier
            }
            PreferenceLayout(
                florisPreferenceModel(),
                modifier = Modifier
                    .padding(innerPadding)
                    .fillMaxWidth()
                    .then(scrollModifier),
                iconSpaceReserved = iconSpaceReserved,
                content = content,
            )
        }
```

2024-05-05 11:32 UTC, patrickgold commented on app/src/main/kotlin/dev/patrickgold/florisboard/app/settings/advanced/AdvancedScreen.kt
> +            title = "Use Material You",
Please add a string resource for this to it is translatable

2024-05-05 14:18 UTC, patrickgold commented
I've just noticed that issue #2032 is still open, could we fix this with this PR as well if we are already completely reworking the color scheme?

2024-05-06 06:27 UTC, lm41 commented
> I've just noticed that issue #2032 is still open, could we fix this with this PR as well if we are already completely reworking the color scheme?

Yes, but this has to be done in the JetPref repo. I'll open a PR

2024-05-06 11:03 UTC, tsiflimagas commented
I've seen that some apps also use `com.mikepenz:aboutlibraries-compose-m3`. It seems that the only change it brings in this case is to make the dependency dialog card and the ok button pill shaped.
Also, it seems that in the theme edit section, the edit and delete buttons are still rectangle shaped. Is this because of the rectangle outline they're in or should they also be pill shaped? 
![Screenshot_20240506-135015_FlorisBoard Debug (1) (1)](https://github.com/florisboard/florisboard/assets/45879751/dfe649dc-9bec-4585-bc58-5aa2edf64977)
Another thing which seems to me could be different is the color and height of the topbar when scrolling down in a section. Just empirically, it seems to me that the text should be below the back button when at the top of the page, and while scrolling, the topbar collapses to a smaller height, the text moves next to the back button, and the topbar's tone changes to a slightly lighter one.
I guess you material3 conventions very well already, so you can assess this. Thank you for your work!

2024-05-06 15:36 UTC, lm41 commented
Thank you for your suggestions :) 
However, the TopAppBar remains a "normal" TopAppBar, as otherwise there is too much empty space for my taste. Only the colors I have now adapted to spec.

2024-05-06 22:46 UTC, tsiflimagas commented
Thank you for implementing the indicated points! 

> However, the TopAppBar remains a "normal" TopAppBar, as otherwise there is too much empty space for my taste

Fair enough, that's reasonable 😀

There are a couple more things that came to my mind:

Do you think those backgrounded "pressed" "focus" "disabled" selectors in theme editor could be made into pill shaped, or would it be misleading resembling pressable buttons? I mean, I think I've seen in other apps such non functional snippets of text being in pill shaped background (like tags maybe), but I don't know if you'd agree with such a design option.
![Screenshot_20240506-232419_FlorisBoard Debug (1)](https://github.com/florisboard/florisboard/assets/45879751/47636562-f431-4462-a02d-5dde3d08350e)


Also, the splashscreen is currently not material You themed. Could this be also taken care of here? 

And the navbar, could it also be coloured? Now it's black. 

Lastly, do you think it would be a good idea to make material You default for A≥12? Many apps which have fully implemented the design, have set it as default, and I think it's reasonable. On a system which entirely follows this design, why not look uniform right away?

2024-05-07 10:20 UTC, lm41 commented
> Do you think those backgrounded "pressed" "focus" "disabled" selectors in theme editor could be made into pill shaped, or would it be misleading resembling pressable buttons?

I have now given the text background some rounder corners. 
> And the navbar, could it also be coloured? Now it's black.

Navbar and status bar now have the same color.
> Lastly, do you think it would be a good idea to make material You default for A≥12? Many apps which have fully implemented the design, have set it as default, and I think it's reasonable. On a system which entirely follows this design, why not look uniform right away?

Good point. I would like to have more opinions on this.
> Edit: also the crash report screen hasn't been converted to m3, but you probably won't think it'a worthwhile adapting it?

The crash report screen has not been converted to JC. It still uses the old layout xml files. I will have a look at this.

2024-05-07 22:21 UTC, patrickgold approved these changes

2024-05-07 22:29 UTC, merged