Fix incorrect smartbar paste button state
florisboard/florisboard pull request #2477
Opened 2024-05-14 14:15 UTC by lm41

Closes  #2415

2024-05-14 15:01 UTC, itsmartashub commented
While you're working on this issue, I was wondering if the last copied item should still be 'pasteable' even after we remove all items from the Florisboard clipboard?
  
If this isn't default behavior but rather a bug, perhaps it's also related to the fact that even when we delete all items from the clipboard, the paste button still maintains that 'active paste' state because the **last copied item** hasn't been removed from some paste "storage" (idk how to named the place where it still hangs)
 
I'm sorry if this isn't the right place to ask.

2024-05-29 05:49 UTC, patrickgold requested changes
Thanks a lot for the changes!

I have reviewed the code and tested out the code, it works really well. My requested changes are only nitpicks or code cleanup, once that's done this is good to merge in.

2024-05-29 05:49 UTC, patrickgold commented on app/src/main/kotlin/dev/patrickgold/florisboard/app/settings/keyboard/KeyboardScreen.kt
> +            entries = IncognitoDisplayMode.listEntries()
```suggestion
            entries = IncognitoDisplayMode.listEntries(),
```

(nitpick)

2024-05-29 05:49 UTC, patrickgold commented on app/src/main/kotlin/dev/patrickgold/florisboard/ime/text/keyboard/TextKeyData.kt
> +        return asString(this, isForDisplay)/*buildString {
Please remove the commented code, as it is present in the internal helper function anyways

2024-05-29 05:49 UTC, patrickgold commented on app/src/main/kotlin/dev/patrickgold/florisboard/ime/text/keyboard/TextKeyData.kt
> +        /*return buildString {
Please remove the commented code, as it is present in the internal helper function anyways

2024-05-29 05:49 UTC, patrickgold commented on app/src/main/kotlin/dev/patrickgold/florisboard/app/AppPrefs.kt
> +            default = IncognitoDisplayMode.DISPLAY_BEHIND_KEYBOARD
```suggestion
            default = IncognitoDisplayMode.DISPLAY_BEHIND_KEYBOARD,
```

(nitpicks)

2024-05-29 20:49 UTC, patrickgold approved these changes

2024-05-29 20:49 UTC, merged