add delete subtype feature
florisboard/florisboard pull request #2580
Opened 2024-09-20 22:40 UTC by Cysiuu

Hello!

I loved this keyboard, so I want to add something from myself. 
When I was adding subtypes I saw that I can't delete them so added a quick solution to delete them on long click.

Also this seems to be from Experimental Api so feel free to correct my solution!

Thanks! 
Again love you work!

![Screenshot_20240921_003952](https://github.com/user-attachments/assets/2ee9457e-c578-458c-870a-17be5d95b534)

2024-09-20 23:00 UTC, lm41 commented
It is possible to delete subtypes (in the top-right corner of the edit subtype screen)
![image](https://github.com/user-attachments/assets/eabfed32-7cc3-4280-aa00-7b51b2e3af48)
Nevertheless, I think this is a good addition to improve the UX. 

In the picture in your comment I can see that you are using `AlertDialog.Builder(context).apply { `, which in this case creates an unstyled dialog. 
Can you please switch to `JetPrefAlertDialog() { }` as this will create a Material3 dialog that matches the rest of the ui. 
This is a composable, so you have to use it in a compose ui context and can't use it directly in the `onLongClick` lamda.

Here is an example on how to use the composable:
https://github.com/florisboard/florisboard/blob/main/app/src/main/kotlin/dev/patrickgold/florisboard/app/ext/ExtensionMaintainerChip.kt#L44-L88

2024-09-21 08:50 UTC, Cysiuu commented
@lm41 
I have made the requested changes in commit 4dfe99d .
Please review the pull request again when you have time. 
Thanks!

![Screenshot_20240921_104731](https://github.com/user-attachments/assets/737ae8ed-6e95-493b-8bc5-08b4ae711f22)

2024-09-21 10:53 UTC, lm41 requested changes
Hello, 
Thank you for quickly adopting my suggestions :D
I have now reworked it a bit and suggested new changes. 
Could you please also add the remaining strings to the translations?

2024-09-21 10:53 UTC, lm41 commented on app/src/main/kotlin/dev/patrickgold/florisboard/app/settings/localization/LocalizationScreen.kt
>  }
```suggestion
fun DeleteSubtypeConfirmationDialog(
    subtypeToDelete: Subtype?,
    onDismiss: () -> Unit,
    onConfirm: () -> Unit,
) {
   subtypeToDelete?.let {
        JetPrefAlertDialog(
            title = "Delete Confirmation",
            confirmLabel = stringRes(R.string.action__yes),
            dismissLabel = stringRes(R.string.action__no),
            onDismiss = onDismiss,
            onConfirm = onConfirm,
        ) {
                Text("Are you sure you want to delete this subtype?")
            }
        }
    }
}
```

2024-09-21 10:53 UTC, lm41 commented on app/src/main/kotlin/dev/patrickgold/florisboard/app/settings/localization/LocalizationScreen.kt
> +        }
```suggestion
        subtypeToDelete = chosenSubtypeToDelete,
        onDismiss = {
            chosenSubtypeToDelete = null
        },
        onConfirm = {
            chosenSubtypeToDelete?.let { subtypeManager.removeSubtype(subtypeToRemove = it) }
            chosenSubtypeToDelete = null
        }
```

2024-09-21 10:53 UTC, lm41 commented on app/src/main/kotlin/dev/patrickgold/florisboard/app/settings/localization/LocalizationScreen.kt
> +                                choosenSubtypeToDelete = subtype
```suggestion
                                chosenSubtypeToDelete = subtype
```

2024-09-21 10:53 UTC, lm41 commented on app/src/main/kotlin/dev/patrickgold/florisboard/app/settings/localization/LocalizationScreen.kt
> +    var choosenSubtypeToDelete: Subtype? by rememberSaveable { mutableStateOf(null) }
```suggestion
    var chosenSubtypeToDelete: Subtype? by rememberSaveable { mutableStateOf(null) }
```

2024-09-21 13:32 UTC, Cysiuu commented
@lm41 
Added the remaining strings to the translations and updated the code based on the suggestions. d60c077
Hope everything is fine! 
Thanks!

2024-09-21 15:34 UTC, lm41 requested changes
Hello,
I just noticed that the app crashes when the dialog is open and the screen is rotated. 
I have made some changes to prevent this.

Also, there are minor formatting nitpicks, but all in all it looks very good.

2024-09-21 15:34 UTC, lm41 commented on app/src/main/kotlin/dev/patrickgold/florisboard/app/settings/localization/LocalizationScreen.kt
> +    var chosenSubtypeToDelete: Subtype? by rememberSaveable { mutableStateOf(null) }
We need to use a custom saver, because the default one crashes the app on rotation.
```suggestion
    var chosenSubtypeToDelete: Subtype? by rememberSaveable(saver = SubtypeSaver) { mutableStateOf(null) }
```

2024-09-21 15:34 UTC, lm41 commented on app/src/main/kotlin/dev/patrickgold/florisboard/app/settings/localization/LocalizationScreen.kt
> +import dev.patrickgold.jetpref.material.ui.JetPrefAlertDialog
This is the custom saver for the mutableState<Subtype?> object
```suggestion
import dev.patrickgold.jetpref.material.ui.JetPrefAlertDialog

internal val SubtypeSaver = Saver<MutableState<Subtype?>, String>(
    save = {
        Json.encodeToString<Subtype?>(it.value)
    },
    restore = {
        mutableStateOf(Json.decodeFromString(it))
    },
)
```

2024-09-21 15:34 UTC, lm41 commented on app/src/main/kotlin/dev/patrickgold/florisboard/app/settings/localization/LocalizationScreen.kt
> +        }
Just a little formatting nit-pick :)
```suggestion
        },
```

2024-09-21 16:00 UTC, Cysiuu commented
@lm41 
Fix applied 75cf9be :)

2024-09-22 00:23 UTC, lm41 approved these changes
Thank you for implementing the changes. They are looking good to me now.
CC: @patrickgold

2024-09-22 12:58 UTC, patrickgold requested changes
Thanks for the PR!

As per [contribution guidelines](https://github.com/florisboard/florisboard/blob/main/CONTRIBUTING.md#translation) PRs must not add or alter translated strings.xml, as those files are automatically written by scripts. Translations must be submitted via Crowdin. Please remove all changes from translated strings.xml files.

2024-09-22 15:10 UTC, Cysiuu commented
> Thanks for the PR!
> 
> As per [contribution guidelines](https://github.com/florisboard/florisboard/blob/main/CONTRIBUTING.md#translation) PRs must not add or alter translated strings.xml, as those files are automatically written by scripts. Translations must be submitted via Crowdin. Please remove all changes from translated strings.xml files.

Sure,  gonna remove it today!  Thanks!

2024-09-22 20:49 UTC, patrickgold approved these changes
By removing translated strings.xml I didn't mean removing ALL strings.xml files, the original is still relevant! But no worries, lm41 and I fixed up the strings.xml issues for you in this PR :)

Other than that the PR looks good to me. Will be part of the 0.4.1 patch release.

2024-09-22 20:50 UTC, merged