add bépo_new, an adaptation of bepo for mobiles
florisboard/florisboard pull request #2603
Opened 2024-09-25 14:07 UTC by MXC48

#2494 
it's my first contribution, tell me if I'm making a mistake

2024-09-28 19:28 UTC, MXC48 commented
Anyone can review ?

2024-09-29 23:25 UTC, patrickgold requested changes
Thanks for your contribution! There is a minor issue with the JSON syntax, else it looks good.

2024-09-29 23:25 UTC, patrickgold commented on app/src/main/assets/ime/keyboard/org.florisboard.layouts/layouts/characters/bepo_new.json
> +    { "$": "auto_text_key", "code":  109, "label": "m" },
```suggestion
    { "$": "auto_text_key", "code":  109, "label": "m" }
```

There is an additional comma which shouldn't be here

2024-10-22 20:53 UTC, patrickgold commented
Hi there!

We're closing this PR because the v0.5 development cycle is about to begin, and it will bring significant changes to the layout code. This would likely cause merge conflicts with your PR. Additionally, custom keyboard layouts will mostly be moved to the addons store with v0.5. We hope you understand and thank you for your contribution!

2024-10-22 20:53 UTC, closed without merging