Auto clean sensitive clipboard items
florisboard/florisboard pull request #2659
Opened 2024-10-24 15:21 UTC by lm41

Closes #2610

2024-10-24 18:23 UTC, lm41 commented on app/src/main/kotlin/dev/patrickgold/florisboard/app/AppPrefs.kt
> +            key = "clipboard__auto_clen_sensitive_after",
Thank you for noticing the typo :D

2024-10-25 12:02 UTC, patrickgold requested changes
Thanks a lot for your changes!

I have reviewed the code changes and have added comments where I'd change/nitpick stuff.

I have one not-yet-tested concern though: What happens when e.g. cleanUpOldAfter=1 and autoCleanSensitiveAfter=60 and both trigger to delete the same clip item concurrently, will it then crash? I currently don't have a device where I can reproduce this exact scenario, maybe you could test that?

2024-10-25 12:02 UTC, patrickgold commented on app/src/main/kotlin/dev/patrickgold/florisboard/app/settings/clipboard/ClipboardScreen.kt
> +                stepIncrement = 5,
```suggestion
                stepIncrement = 10,
```

I feel like with 10 it is easier to set to the desired value and it is still fine-grained enough for custom values

2024-10-25 12:18 UTC, lm41 commented on app/src/main/kotlin/dev/patrickgold/florisboard/app/settings/clipboard/ClipboardScreen.kt
> +                title = "Auto clean sensitive items",
Oopsi :grin:

2024-10-25 14:45 UTC, patrickgold approved these changes
thanks for the fixes, lgtm now

2024-10-25 14:46 UTC, merged